version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loginapi
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

  loginapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/loginapi
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    ports:
      - "8085:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
