version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: defaultdb  # Ensure this matches the database name in Aiven MySQL
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network

  loginapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-api-mysql-api.e.aivencloud.com:21759/defaultdb
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_D-HEeoh54hmvlOlJ5mW
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SERVER_PORT: "8080"  # Use SERVER_PORT instead of server.port for Docker
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
